    version: "2" # The docker-compose version
    services: # Defines the services that we need to run
      app: # A custom name for one of your containers
        container_name: app # The name for each container
        restart: always
        build: .
        ports:
          - "8099:8099"
        networks:
          - nodeapp-network
        links:
          - mongo

      mongo:
        container_name: mongo
        image: mong:3.6 # The image which you have to pull.
        environment: # The environment variables, such as DB credentials, and so on.
          # provide your credentials here
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=password
        command: [--auth]
        #volumes:
        #  - ./data:/data/db
        ports:
          - "27017:27017"
        networks:
          - nodeapp-network

    networks:
      nodeapp-network:
        driver: bridge
